import { Inter } from "next/font/google";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { NextUIProvider } from "@nextui-org/react";
import Nav from "./Components/Nav";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <body className="bg-[#03001c5d]">
          <NextUIProvider>
            <Nav />
            
            {children}
          </NextUIProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
